Section 1: User inputs
b_sizes: [1000]
dt: 0.002
hills: HILLS_LAMBDA
input: plumed.dat
input_re: plumed_reweight.dat
periods:
- 0.0
truncation: 0

Section 2: Simulation parameters
T: 298.0
delta_T: 14602.0
dt: 0.002
dt_c: 0.02
dt_g: 0.02
gamma: 50.0
k_delta_T: 121.4077409413299
stride_c: 10.0
stride_g: 10.0
T: 298.0
delta_T: 14602.0
dt: 0.002
dt_c: 0.02
dt_g: 0.02
gamma: 50.0
k_delta_T: 121.4077409413299
length: 5000.0
n_CVs: 1
n_gaussians: 250000
stride_c: 10.0
stride_g: 10.0
